# Backend Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend files to the container
COPY src /app/src
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 for the backend
EXPOSE 8000

# Command to run the backend
CMD ["uvicorn", "src.app.combined_api:app", "--host", "0.0.0.0", "--port", "8000"]
